**File handling (Text File)**

In [ ]:
file = open("Python.txt","w")
file.close()

In [ ]:
file = open("Python.txt","r")
x = file.read()
print(x)
file.close()


this is my program



In [ ]:
file = open("Python.txt","r")
x = file.readline()
for i , y in enumerate(x):
  print(i+1,y,end='')
file.close()

1 t2 h3 i4 s5  6 i7 s8  9 m10 y11  12 p13 r14 o15 g16 r17 a18 m19 


In [ ]:
def file_read_from_head(fname, nlines):
        from itertools import islice
        with open(fname) as f:
                for line in islice(f, nlines):
                        print(line)
file_read_from_head('Python.txt',2)


this is my program

hii



**WAP to read the first n lines of a file**

In [ ]:
file = open("Python.txt","r")
x = file.readlines()
num = int(input("Enter num of lines to be read"))
for i,y in enumerate(x):
    if(i+1<=num):
        print(y, end=" ")
    
file.close()


Enter num of lines to be read2
this is my program
 hii
 

**WAP to read the last n lines of a file**

In [ ]:
file = open("Python.txt","r")
a=int(input("no of line "))

#for i in range(a):
for line in (file.readlines() [-nol:]): 
    print(line)
file.close

no of line 2
hello

this is good


<function TextIOWrapper.close>

**WAP to print the sum of the content of a file**

In [ ]:
file = open("INT.txt","w")
file.close()

In [ ]:
a = open('INT.txt', 'r') 
content = a.readlines() 
s = 0
for line in content:
  for i in line:
    if(i.isdigit() == True):
      s += int(i) 

print("The sum is:", s) 


The sum is: 70


**WAP to print the longest word in the whole line**

In [ ]:
def longest_words(filename):
    with open(filename, 'r') as infile:
        words = infile.read().split()
    max_len = len(max(words, key=len))
    return [word for word in words if len(word) == max_len]
 
print(longest_words('Longword.txt'))

['circumstances.']


In [ ]:
file = open("Longword.txt","w")
file.close()

**WAP to print the content of a file in two diff o/p files**

In [5]:
file = open('abc.txt','w')
file.close()

In [6]:
with open('abc.txt', 'r') as f:
   lines = f.readlines()
even_lines, odd_lines = lines[::2], lines[1::2]

with open('abc1.txt','w') as f1:
   for odd_line in odd_lines:
       f1.write(odd_line)

with open('abc2.txt','w') as f2:
   for even_line in even_lines:
     f2.write(even_line)

**File handling (Binary File)**

In [ ]:
import urllib.request
infile = urllib.request.urlopen("https://www.youtube.com/")
print(infile.read().decode())

<!DOCTYPE html><html style="font-size: 10px;font-family: Roboto, Arial, sans-serif;" lang="en"><head><meta http-equiv="X-UA-Compatible" content="IE=edge"/><script nonce="ByTjKHFtO3LOkXCsgFv0bQ">var ytcfg={d:function(){return window.yt&&yt.config_||ytcfg.data_||(ytcfg.data_={})},get:function(k,o){return k in ytcfg.d()?ytcfg.d()[k]:o},set:function(){var a=arguments;if(a.length>1)ytcfg.d()[a[0]]=a[1];else for(var k in a[0])ytcfg.d()[k]=a[0][k]}};
window.ytcfg.set('EMERGENCY_BASE_URL', '\/error_204?t\x3djserror\x26level\x3dERROR\x26client.name\x3d1\x26client.version\x3d2.20210202.08.03');</script><script nonce="ByTjKHFtO3LOkXCsgFv0bQ">(function(){window.yterr=window.yterr||true;window.unhandledErrorMessages={};window.unhandledErrorCount=0;
window.onerror=function(msg,url,line,columnNumber,error){var err;if(error)err=error;else{err=new Error;err.stack="";err.message=msg;err.fileName=url;err.lineNumber=line;if(!isNaN(columnNumber))err["columnNumber"]=columnNumber}var message=String(err.messa

In [ ]:
import pickle 
filename = 'bin.txt'
dogs_dict = {'I':9};
outfile = open(filename,'wb')
pickle.dump(dogs_dict,outfile)
outfile.close()


In [ ]:
import numpy

In [ ]:
import numpy as np
np.array([3.14,4,2,3])

array([3.14, 4.  , 2.  , 3.  ])

In [ ]:
x = np.array(range(1,10))
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
y = x.reshape((3,3))
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])